name: CarbonPHP Feature Test Suit

on:
  push:
    # @link https://nvie.com/posts/a-successful-git-branching-model/
    branches:
      - main

jobs:
  Linux:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{matrix.operating-system}}
    container: ${{matrix.container}}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '8.2' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstri ng, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
          tools: php-cs-fixer, phpunit
        env:
          update: true # specify true or false

      - name: service  --status-all
        run: service  --status-all

      - name: sudo systemctl start mysql.service
        run: sudo systemctl start mysql.service

      - name: echo -e "[client]\n user=root \n password=root \n host=localhost" > `pwd`/mysql.cnf
        run: echo -e "[client]\n user=root \n password=root \n host=localhost" > `pwd`/mysql.cnf

      - name: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e "create database \`ReactBoot\`"
        run: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e "create database \`ReactBoot\`"

      - name: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e  "GRANT ALL PRIVILEGES ON ReactBoot. * TO 'root'@'localhost';"
        run: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e  "GRANT ALL PRIVILEGES ON ReactBoot. * TO 'root'@'localhost';"

      - name: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e  "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';"
        run: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e  "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';"

      - name: composer validate
        run: composer validate

      - name: composer install --prefer-dist --no-progress --no-scripts
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: php index.php buildDatabase -r
        run: php index.php buildDatabase -r

      - name: php index.php rest
        run: php index.php rest

      - name: ./vendor/se/selenium-server-standalone/composer/bin/selenium-server-standalone &
        run: ./vendor/se/selenium-server-standalone/composer/bin/selenium-server-standalone &

        # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
        # Docs: https://getcomposer.org/doc/articles/scripts.md
      # - name: composer run test (Run test suite)
      #  run: composer run test
